### ISSUE TITLE
Bleadperl breaks Archive-Zip-SimpleZip test suite

### ISSUE THREAD

**Issue by jkeenan** [pmqs/Archive-Zip-SimpleZip#20]
See, e.g., http://www.cpantesters.org/cpan/report/92018894-64d1-11ef-9d1a-d11d79ec3515.

This is probably due to the long scheduled removal of the apostrophe as package separator and from variable names.  This went into Perl 5 blead earlier this month and will appear in monthly dev release perl-5.41.3, scheduled for this week.

This distribution relies on bundled -- hence, **old** -- versions of Test::Builder, Test::More and Test::Simple.  Unless you *absolutely* rely on these versions, please consider scrapping them and relying on the versions of those modules which ship with Perl 5 core.

**Comment by pmqs** [comment]
Thanks @jkeenan -- has spotted the failures on cpantesters, but thanks for the reminder.

Good point about not actually needing to ship the `Test::*` modules. Probably inherited them  from whatever other module of mine I used as a template when creating this one.

I'll probably go with that, rather than the PR in #21

**Comment by pmqs** [comment]
version 1.001 uploaded to GitHub & CPAN with the Test* modules removed
